spring:
  config:
    import: aws-parameterstore:/param/aws-member-manager/prod/

  # AWS 관련
  cloud:
    aws:
      s3:
        enabled: true
        bucket : ${S3_BUCKET_NAME}
      region:
        static: ap-northeast-2
      parameterstore:
        enabled: true

  servlet:
    multipart:
      max-file-size: 10MB

  # DB 관련
  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_TABLE_NAME}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false


# actuator 관련
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

  endpoint:
    health:
      show-details: never

logging:
  level:
    root: info

info:
  team-name : ${TEAM_NAME}

use-s3-for-profile: true

